// This file is auto-generated by @hey-api/openapi-ts

export const ChatModelSchema = {
  type: 'string',
  enum: [
    'chatgpt-4o-latest',
    'claude-3-5-sonnet-20241022',
    'yi-lightning',
    'deepseek-chat',
    'gemini'
  ]
} as const

export const ImageModelSchema = {
  type: 'string',
  enum: ['dall-e', 'stable-diffusion', 'dreamshaper_8_93211.safetensors']
} as const

export const MessageSchema = {
  type: 'object',
  properties: {
    role: {
      type: 'string',
      description: "The role of the message sender (e.g., 'user', 'assistant')."
    },
    content: {
      type: 'string',
      description: 'The content of the message.'
    }
  }
} as const
